spring:
  datasource:
    url: ${DATABASE_URL}

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

logging:
  level:
    com.example.observationcalendar: INFO
    com.example.observationcalendar.mapper: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN